server {
    listen 8090;
    listen [::]:8090;
    server_name _;
    root /var/www/chinois;
    index index.html;
    client_max_body_size 400k;
    location = /api.php {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    }
    location ~ \.php$ { return 404; }
    location / { try_files $uri /index.html; }
}
